# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        #dev:
            #pattern: ^/(_(profiler|wdt)|css|images|js)/
            #pattern:    ^/
            #security: true
            #http_basic:
                #realm: "Secured Demo Area"

        #main:
         #   anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        secured_area:
            pattern:    ^/
            anonymous: true
            provider:  my_db_provider
            http_basic:
                realm: "Secured Area"

    access_control:
        - { path: /manage/*, roles: ROLE_ADMIN }

    providers:
        my_db_provider:
            entity:
                class: lamartineStoreBundle:Users
                property: username
        #in_memory:
         #    memory:
          #      users:
           #         ryan:  { password: ryanpass, roles: 'ROLE_USER' }
            #        admin: { password: kitten, roles: 'ROLE_ADMIN' }

    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        lamartine\StoreBundle\Entity\Users:
            algorithm: bcrypt
            cost: 12