lamartine_store_homepage:
    path:     /test/{name}
    defaults: { _controller: lamartineStoreBundle:Default:index }
lamartine_addUser_page:
    path:     /addUser/
    defaults: { _controller: lamartineStoreBundle:Default:addUser }
lamartine_addNote_page:
    path:     /addNote/
    defaults: { _controller: lamartineStoreBundle:Default:addNote }